services:
  simulator:
    build:
      context: ./simulator
    networks:
      - ditto_network
    depends_on:
      - mongo
    env_file:
      - .env

  indexer:
    build:
      context: ./indexer
    networks:
      - ditto_network
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo:latest
    command: mongod --replSet rs0 --bind_ip_all
    networks:
      - ditto_network
    volumes:
      - mongo-data:/data/db

  mongo-init:
    image: mongo:latest
    restart: "no"
    depends_on:
      - mongo
    command: >
      bash -c "sleep 5 && mongosh --host mongo --port 27017 --eval 'rs.initiate({_id: \"rs0\", members: [{_id: 0, host: \"mongo:27017\"}]})'"
    networks:
      - ditto_network

networks:
  ditto_network:
    driver: bridge

volumes:
  mongo-data: 