services:
  simulator:
    image: ghcr.io/dittonetwork/simulator:0.0.5
    networks:
      - ditto_network
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/?replicaSet=rs0
      - DB_NAME=indexer
      - MAX_WORKERS=4
      - RUNNER_NODE_SLEEP=5
      - FULL_NODE=false
      - MAX_MISSING_NEXT_SIM_LIMIT=100
      - MAX_BLOCK_RANGE_11155111=10000
      - MAX_BLOCK_RANGE_1=2000
      - IPFS_SERVICE_URL=https://ipfs-service.dittonetwork.io
      - IS_PROD=true
      - LOG_LEVEL=info
      - LOG_PRETTY=true
      - API_ONLY=true
      - EXECUTOR_ADDRESS=0xF177179963aA0EDE80Be4396d04d970171CF6a36

  othnode:
    build:
      context: .
      dockerfile: Dockerfile.othnode
    restart: always
    env_file:
      - .env
    networks:
      - ditto_network
    command: [
      "run",
      "attester",
      "/dns4/aggregator.dittonetwork.io/tcp/9876/p2p/12D3KooWDq8na78bZGZGcVeNZqXRKm6rASCy2L3rerYBQD8yrA1J",
      "--avs-webapi",
      "http://simulator",
      "--avs-webapi-port",
      "8080",
      "--p2p.port",
      "9876",
    ]
    ports:
      - "9876:9876"
    environment:
      - PRIVATE_KEY=${EXECUTOR_PRIVATE_KEY}
      - L1_CHAIN=mainnet
      - L2_CHAIN=mainnet-l2,polygon,base,arbitrum-one
      - OTHENTIC_BOOTSTRAP_ID=12D3KooWDq8na78bZGZGcVeNZqXRKm6rASCy2L3rerYBQD8yrA1J
      - AVS_GOVERNANCE_ADDRESS=0x4a49d2E53B33a4D50024B99B4fA159041367E55D
      - ATTESTATION_CENTER_ADDRESS=1@0x9969F9eBD5210679d0b33d4e820283583a1caFA8,137@0x4Ee221703be5554Af803B469C678Bbd02797bb82,8453@0xf145D2527b74ADdc6A58C4e5A66C5cC249e8fE72,42161@0x0DcC81038Ab43EFe74f7869c04B9C93983501C88
      - L1_RPC=${RPC_URL_1}
      - L2_RPC=1@${RPC_URL_1},137@${RPC_URL_137},8453@${RPC_URL_8453},42161@${RPC_URL_42161}
    depends_on:
      simulator:
        condition: service_started

  indexer:
    image: ghcr.io/dittonetwork/indexer:0.0.3
    networks:
      - ditto_network
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/?replicaSet=rs0
      - DB_NAME=indexer
      - META_FILLER_SLEEP=2
      - IPFS_CONNECTOR_ENDPOINT=https://ipfs-service.dittonetwork.io/ipfs/read
      - ENV=prod

  mongo:
    image: mongo:8.0.13
    command: mongod --replSet rs0 --bind_ip_all
    networks:
      - ditto_network
    volumes:
      - mongo-data:/data/db

  mongo-init:
    image: mongo:8.0.13
    restart: "no"
    depends_on:
      - mongo
    command: >
      bash -c "sleep 5 && mongosh --host mongo --port 27017 --eval 'rs.initiate({_id: \"rs0\", members: [{_id: 0, host: \"mongo:27017\"}]})'"
    networks:
      - ditto_network

networks:
  ditto_network:
    driver: bridge

volumes:
  mongo-data: 
