services:
  simulator:
    build:
      context: ./simulator
    networks:
      - ditto_network
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/?replicaSet=rs0
      - DB_NAME=indexer
      - RPC_URL=...
      - DEFAULT_RPC_URL_SEPOLIA=...
      - MAX_WORKERS=1
      - RUNNER_NODE_SLEEP=60
      - FULL_NODE=false
      - MAX_MISSING_NEXT_SIM_LIMIT=100
      - MAX_BLOCK_RANGE_11155111=10000
      - MAX_BLOCK_RANGE_1=2000
      - EXECUTOR_PRIVATE_KEY=...
      - CHAIN_ID=11155111
      - IPFS_SERVICE_URL=https://ipfs-service.develop.dittonetwork.io
      - WORKFLOW_CONTRACT_ADDRESS=0x5CE5E78588F4dC8556E2c607134e8b76567AECE6
      - LOG_LEVEL=info
      - LOG_PRETTY=true 

  indexer:
    build:
      context: ./indexer
    networks:
      - ditto_network
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/?replicaSet=rs0
      - DB_NAME=indexer
      - META_FILLER_SLEEP=2
      - IPFS_CONNECTOR_ENDPOINT=https://ipfs-service.develop.dittonetwork.io/ipfs/read
      - RPC_11155111=...

  mongo:
    image: mongo:latest
    command: mongod --replSet rs0 --bind_ip_all
    networks:
      - ditto_network
    volumes:
      - mongo-data:/data/db

  mongo-init:
    image: mongo:latest
    restart: "no"
    depends_on:
      - mongo
    command: >
      bash -c "sleep 5 && mongosh --host mongo --port 27017 --eval 'rs.initiate({_id: \"rs0\", members: [{_id: 0, host: \"mongo:27017\"}]})'"
    networks:
      - ditto_network

networks:
  ditto_network:
    driver: bridge

volumes:
  mongo-data: 